package org.routingplatform.app.security

import android.content.Context
import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import org.json.JSONArray
import org.json.JSONObject
import java.nio.charset.StandardCharsets
import java.nio.file.Files
import java.nio.file.StandardCopyOption
import java.io.FileOutputStream
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/**
 * Local encrypted evidence store. No network capability is present here.
 * AES-GCM supplies confidentiality and authentication; the non-exportable key
 * is generated by Android Keystore.
 */
class AndroidKeystoreEvidenceStore(context: Context) : DrivingInterferenceEvidenceStore {
    private val appContext = context.applicationContext
    private val file = java.io.File(appContext.noBackupFilesDir, "driving-interference-evidence.v2")

    init {
        // v1 did not bind its schema as AES-GCM AAD and is intentionally not parsed as v2.
        java.io.File(appContext.noBackupFilesDir, "driving-interference-evidence.v1").delete()
    }

    @Synchronized
    override fun append(record: DrivingInterferenceEvidenceRecord) {
        val records = readAll().toMutableList()
        records += record
        writeAll(DrivingInterferenceRetention.retained(records, record.utcEpochMillis))
    }

    @Synchronized
    override fun readForAuthenticatedAdmin(nowUtcEpochMillis: Long): List<DrivingInterferenceEvidenceRecord> {
        val stored = readAll()
        val retained = DrivingInterferenceRetention.retained(stored, nowUtcEpochMillis)
        if (retained.size != stored.size) writeAll(retained)
        return retained
    }

    @Synchronized
    override fun purgeExpired(nowUtcEpochMillis: Long) {
        writeAll(DrivingInterferenceRetention.retained(readAll(), nowUtcEpochMillis))
    }

    private fun key(): SecretKey {
        val store = KeyStore.getInstance("AndroidKeyStore").apply { load(null) }
        (store.getKey(KEY_ALIAS, null) as? SecretKey)?.let { return it }
        val generator = KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, "AndroidKeyStore")
        generator.init(
            KeyGenParameterSpec.Builder(
                KEY_ALIAS,
                KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT,
            ).setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                .setKeySize(256)
                .build()
        )
        return generator.generateKey()
    }

    private fun readAll(): List<DrivingInterferenceEvidenceRecord> {
        if (!file.exists()) return emptyList()
        require(file.length() in (IV_BYTES + 1)..MAX_FILE_BYTES) { "Invalid security evidence size" }
        if (file.length() > MAX_FILE_BYTES) throw SecurityException("Security evidence store exceeds local safety bound")
        val bytes = file.readBytes()
        require(bytes.size > IV_BYTES)
        val iv = bytes.copyOfRange(0, IV_BYTES)
        val encrypted = bytes.copyOfRange(IV_BYTES, bytes.size)
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.DECRYPT_MODE, key(), GCMParameterSpec(128, iv))
        cipher.updateAAD(AAD)
        val array = JSONArray(String(cipher.doFinal(encrypted), StandardCharsets.UTF_8))
        return (0 until array.length()).map { decode(array.getJSONObject(it)) }
    }

    private fun writeAll(records: List<DrivingInterferenceEvidenceRecord>) {
        val array = JSONArray()
        records.forEach { array.put(encode(it)) }
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.ENCRYPT_MODE, key())
        cipher.updateAAD(AAD)
        val encrypted = cipher.doFinal(array.toString().toByteArray(StandardCharsets.UTF_8))
        val tmp = java.io.File(file.parentFile, file.name + ".tmp")
        FileOutputStream(tmp).use { out -> out.write(cipher.iv); out.write(encrypted); out.fd.sync() }
        try {
            Files.move(tmp.toPath(), file.toPath(), StandardCopyOption.ATOMIC_MOVE, StandardCopyOption.REPLACE_EXISTING)
        } catch (failure: Exception) {
            tmp.delete()
            throw java.io.IOException("Unable to atomically persist security evidence", failure)
        }
    }

    private fun encode(r: DrivingInterferenceEvidenceRecord) = JSONObject()
        .put("id", r.eventId).put("payloadDigest", r.payloadDigest).put("kind", r.kind.name).put("utc", r.utcEpochMillis)
        .put("elapsed", r.elapsedRealtimeNanos).put("session", r.sessionReference)
        .put("source", r.source).put("action", r.action).put("integrity", r.integrityState)
        .apply {
            r.vehiclePosition?.let { p ->
                put("position", JSONObject().put("lat", p.latitude).put("lon", p.longitude)
                    .put("accuracy", p.accuracyM).put("observed", p.observedElapsedRealtimeNanos))
            }
        }

    private fun decode(o: JSONObject): DrivingInterferenceEvidenceRecord {
        val p = o.optJSONObject("position")?.let {
            EvidenceVehiclePosition(it.getDouble("lat"), it.getDouble("lon"), it.getDouble("accuracy"), it.getLong("observed"))
        }
        return DrivingInterferenceEvidenceRecord(
            o.getString("id"), o.getString("payloadDigest"), DrivingInterferenceKind.valueOf(o.getString("kind")),
            o.getLong("utc"), o.getLong("elapsed"), o.getString("session"),
            o.getString("source"), o.getString("action"), o.getString("integrity"), p,
        )
    }

    companion object {
        private const val KEY_ALIAS = "routing_platform_driving_evidence_v2"
        private const val TRANSFORMATION = "AES/GCM/NoPadding"
        private const val IV_BYTES = 12
        private const val MAX_FILE_BYTES = 8L * 1024L * 1024L
        private const val MAX_FILE_BYTES = 4L * 1024L * 1024L
        private val AAD = "routing-platform:driving-evidence:v2".toByteArray(StandardCharsets.UTF_8)
    }
}
